global:
  scrape_interval: 10s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - 'node-exporter:9100'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093